---
- name: Add cron to delete directories of successful jobs older than 60 minutes
  cron:
    name: "delete successful directories"
    minute: "21"
    hour: "*/2"
    job: "find {{ pulsar_data_path }}/staging/*/postprocessed -type f -amin +60 -exec dirname {} \\; | xargs rm -rf "

- name: Add cron to delete directories of unsuccessful jobs older than 10 days
  cron:
    name: "delete unsuccessful directories"
    minute: "21"
    hour: "3"
    job: "find {{ pulsar_data_path }}/staging/ -maxdepth 1 -mindepth 1 -type d -ctime +10 -exec rm -rf {} +"

- name: Add cron to restart pulsar
  cron:
    name: "restart Pulsar to take care of RabbitMQ shutdown issue"
    minute: "11"
    hour: "6"
    job: "sudo systemctl restart pulsar"