# Sample file for testing run-data-managers
genomes:
    - accession: NC_001617.1
      name: RhinoVirus A (NC_001617.1)
      id: RhinoVirusA

data_managers:
    - id: data_manager_fetch_genome_all_fasta_dbkey
      params:
        - 'dbkey_source|dbkey_source_selector': 'new'
        - 'dbkey_source|dbkey': '{{ item.id }}'
        - 'dbkey_source|dbkey_name': '{{ item.name }}'
        - 'sequence_name': '{{ item.name }}'
        - 'sequence_id': '{{ item.id }}'
        - 'reference_source|reference_source_selector': 'ncbi'
        - 'reference_source|requested_identifier': '{{ item.accession }}'
      items: "{{ genomes }}"
      data_table_reload:
        - all_fasta
        - __dbkeys__
