---
sudo: required
dist: xenial

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.7.6.0
  - ANSIBLE_VERSION=2.6.12.0
  - ANSIBLE_VERSION=2.5.14.0
  - ANSIBLE_VERSION=2.4.6.0
  - ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.2.3.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

  # Remove fail2ban
  - sudo apt-get remove --purge --yes fail2ban

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml || true; fi

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
