system_groups:
  - { name: galaxy, gid: 1024, group_names: ["galaxyserver", "slurm"] }
  - { name: slurm, gid: 1025, group_names: ["galaxyserver", "slurm"] }
  - { name: docker, gid: 1028, group_names: ["galaxyserver", "slurm"] }

system_users:
  - {
      name: galaxy,
      uid: 1024,
      group: galaxy,
      shell: /bin/bash,
      create_home: yes,
      groups: ["docker"],
      group_names: ["galaxyserver", "slurm"],
    }
  - {
      name: slurm,
      uid: 1025,
      group: slurm,
      shell: /sbin/nologin,
      create_home: no,
      group_names: ["galaxyserver", "slurm"],
    }

galaxy_host: "{{ groups['galaxyserver'][0] }}"
galaxy_ip: "{{ hostvars[galaxy_host].ansible_host }}"

galaxy_admin_email_to: "admin@usegalaxy.no"
galaxy_admin_email_from: "admin@usegalaxy.no"
galaxy_admin: "admin@usegalaxy.no"

db_host: "{{ groups['database'][0] }}"
db_ip: "{{ hostvars[db_host].ansible_host }}"
galaxy_db_user: "galaxy"
# Database name is in all.yml

slurm_host: "{{ groups['slurm'][0] }}"
slurm_ip: "{{ hostvars[slurm_host].ansible_host }}"

smtp_host: "mail.usegalaxy.no"

# variables generated based on the information above, should only need to edit in extreme cases
db_connection: "postgresql://{{galaxy_db_user}}:{{galaxy_db_passwd}}@{{db_host}}/{{galaxy_database}}"
# certs for the frontend
#ssl_cert: "/etc/letsencrypt/live/{{galaxy_host}}/fullchain.pem"
#ssl_key: "/etc/letsencrypt/live/{{galaxy_host}}/privkey.pem"
#ssl_chain: "/etc/letsencrypt/live/{{galaxy_host}}/chain.pem"

gpg_key_name: "admin@usegalaxy.no"

# system.yml

dhclient_interface: "{{ ansible_default_ipv4.interface }}"
dhclient_config:
  - "timeout 300;"
  - "retry 60;"
  - 'supersede domain-search "usegalaxy.no";'

# Postfix
postfix_relayhost: "{{ smtp_host }}" # TODO: Make sure this works
postfix_aliases:
  - user: root
    alias: kim.brugger@uib.no
  - user: admin
    alias: root
  - user: usegalaxy
    alias: contact@bioinfo.no
  - user: abuse
    alias: root
postfix_smtp:
  tls_CApath: "/etc/pki/tls/certs"
  tls_security_level: "may"
  tls_cert_file: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
  tls_key_file: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
  tls_note_starttls_offer: "yes"

# Sudo access
sudo_defaults:
  - name: telegraf
    defaults: "!logfile, !syslog, !pam_session"
sudo_users:
  - name: telegraf
    nopasswd: yes
    commands:
      - "/usr/bin/fail2ban-client status"
      - "/usr/bin/fail2ban-client status *"
