pulsar_virtualenv_command: virtualenv-3

pulsar_user: pulsar
pulsar_group: pulsar

pulsar_data_path: /mnt/users/usegalaxy_no
pulsar_server_dir: '{{ pulsar_data_path }}/server'
pulsar_venv_dir: '{{ pulsar_data_path }}/venv'
pulsar_config_dir: '{{ pulsar_data_path }}/config'
pulsar_staging_dir: '{{ pulsar_data_path }}/staging'
pulsar_cache_dir: '{{ pulsar_data_path }}/cache'
pulsar_systemd: true

pulsar_rabbitmq_username: nmbu_galaxy
pulsar_rabbitmq_password: "{{ rabbitmq_password_galaxy_nmbu }}"
pulsar_rabbitmq_vhost: pulsar_nmbu_orion
pulsar_private_token: "{{ pulsar_nmbu_private_token }}"
pulsar_rabbitmq_proxy: "{{ groups['database'][0] }}"

pulsar_create_user: false

#pulsar_message_queue: "amqps://{{ pulsar_rabbitmq_username}}:{{ pulsar_rabbitmq_password}}@{{ pulsar_rabbitmq_proxy }}/%2F{{ pulsar_rabbitmq_vhost }}"
pulsar_message_queue: "pyamqp://{{ pulsar_rabbitmq_username }}:{{ rabbitmq_password_galaxy_nmbu }}@{{ pulsar_rabbitmq_proxy }}//{{ pulsar_rabbitmq_vhost }}?ssl=1"

pulsar_optional_dependencies:
  # - pyOpenSSL
  # For remote transfers initiated on the Pulsar end rather than the Galaxy end
  # Does not work, needs to be installed with --install-option="--with-nss"
  #- pycurl
  # uwsgi used for more robust deployment than paste
  - uwsgi
  # drmaa required if connecting to an external DRM using it.
  - drmaa
  # kombu needed if using a message queue
  - kombu
  # requests and requests_toolbelt for remote staging and pycurl is unavailable, poster is not working for python3
  - requests
  - requests_toolbelt
  # psutil and pylockfile are optional dependencies but can make Pulsar
  # more robust in small ways.
  - psutil
  - pylockfile

pulsar_drmaa_library_path: /local/genome/packages/slurm-drmaa/1.1.0/lib/libdrmaa.so

pulsar_yaml_config:
  dependency_resolvers_config_file: dependency_resolvers_conf.xml
  conda_auto_init: True
  conda_auto_install: True
  staging_directory: "{{ pulsar_staging_dir }}"
  message_queue_url: "{{ pulsar_message_queue }}"
  managers:
    _default_:
      type: queued_drmaa
      native_specification: "--nodes=1 --partition=smallmem,cigene,hugemem --ntasks=1 --mem=8000"
