telegraf_database: usegalaxy
telegraf_username: usegalaxy

# Install the latest version of Telegraf
telegraf_agent_package_state: latest

telegraf_agent_hostname: "{{ inventory_hostname }}"
telegraf_agent_interval: "60" # seconds

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = {{ telegraf_urls }}
      - database = "{{ telegraf_database }}"
      - username = "{{ telegraf_username }}"
      - password = "{{ telegraf_password }}"

#example config, needs to be determined later on
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = false
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: chrony
  - plugin: fail2ban
    config:
      - use_sudo = true
