---

- name: Create/invoke script virtualenv (Data managers)
  pip:
    name:
      - ephemeris==0.8.0  # Pinned version should make sure ephemeris version matches what the role has been tested with
      - bioblend==0.10.0
    state: present
    virtualenv: "{{ galaxy_tools_base_dir }}/venv"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"

- name: Copy galaxy_tools_data_managers_list in venv
  copy: src="{{ galaxy_tools_data_managers_list }}" dest="{{ galaxy_tools_base_dir }}/venv/bin/data_managers_list.yaml"

- name: Install Data-managers and Genomes
  command: '{{ galaxy_tools_base_dir }}/venv/bin/run-data-managers -a "{{ galaxy_tools_api_key }}" -g "{{ galaxy_tools_galaxy_instance_url }}" --config "{{ galaxy_tools_base_dir }}/venv/bin/data_managers_list.yaml" '
  register: install_result
  changed_when: "install_result.stderr.find('Failed jobs: 0') != -1"
  failed_when: "(install_result.stderr.find('Tool not found or not accessible') != -1) or not(install_result.stderr.find('Failed jobs: 0') != -1) or (install_result.rc != 0)"
  ignore_errors: "{{ galaxy_tools_ignore_errors }}"
  notify:
    - ansible-galaxy-tools restart galaxy
    
- name: Display data_managers results
  debug:
    msg:
      - "{{ install_result.stderr }}"
      - "{{ install_result.stdout }}"
      
