# set outer loop's filename as a fact
- name: get tool list
  include_vars: "{{ tool_list_file }}"

- name: Install Tool Shed tools
  command: '{{ galaxy_tools_base_dir }}/venv/bin/shed-tools install -y "{{ item | to_nice_yaml }}" -a "{{ galaxy_tools_api_key }}" -g "{{ galaxy_tools_galaxy_instance_url }}"'
  register: install_result
  changed_when: "'installed successfully' in install_result.stderr"
  failed_when: ('Error installing' in install_result.stderr) or ('Missing required' in install_result.stderr) or (install_result.rc != 0)
  ignore_errors: "{{ galaxy_tools_ignore_errors }}"
  notify:
    - ansible-galaxy-tools restart galaxy
  with_items:
    - "{{ tools }}"
